# Generated by Django 4.2.29 on 2026-03-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('GENERAL', 'General Consultation'), ('SECOND_OPINION', 'Free Second Opinion'), ('INSURANCE', 'Insurance Help'), ('MEDICAL_OPINION', 'Medical Opinion')], default='GENERAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
