# Generated by Django 4.2.29 on 2026-03-28 09:42

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NET_BANKING', 'Net Banking'), ('PAY_AT_HOSPITAL', 'Pay at Hospital')], default='UPI', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('149.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
