# Generated by Django 4.2.29 on 2026-03-28 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_doctorprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_file',
            field=models.FileField(blank=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
